### ISSUE TITLE
"Here, we list all subfolders in the root directory,"

### ISSUE THREAD

**Issue by paul-hammant** [umlet/pwk#2]
> We can use pwk in an awk-like way. Here, we list all subfolders in the root directory, and ignore exceptions on files not being directories:

This one gives a dump to the console that, as an example of use, doesn't map to things people might want to do regularly:

```
[]
[]
['prepared', 'data8']
['vagrant', 'X11']
['etc', 'var', 'tmp', 'tftpboot']
```

I don't think people need a list of the **contents of the** (language improvement) subfolders of the root directory, in that style. 

Could this be replaced with a better example? Something more fitting if a **pipe-using** sequence of unix commands?

**Comment by umlet** [comment]
True -- the content of the example is useless. I was looking for a way to start a stdin stream that is short and works for everyone ("ls -l"), followed by Python that throws an exception on some and only some parts of that stream (os.listdir).. any idea on a more useful example that has stdin and partial exceptions?
(I will clarify the ambiguous description otherwise..)

**Comment by paul-hammant** [comment]
Feels like two sets of examples - one or more examples of something semi-popular in a pipe sequence. Something from http://www.bashoneliners.com maybe ... that'd be more elegant in pwk?

Then a single one that could be more contrived for the exception case.

**Comment by umlet** [comment]
Clarified text.
